#%RAML 1.0 NamedExample
Users:
  -
    username: jackpeters
    fullname: Jack Peters
    birthday: 11-06-1985
    gender: male
    dateRegistered: 25-09-2014
  -
    username: john123
    fullname: John White Smith
    birthday: 11-06-1984
    gender: male
    dateRegistered: 25-09-2012